# Generated by Django 5.2.1 on 2025-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
