# Generated by Django 5.2.1 on 2025-06-25 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0002_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_diario_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
