# Generated by Django 5.2.1 on 2025-06-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0003_agendamento_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbeiroIndisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='barbearia_app.barbeiro')),
            ],
            options={
                'verbose_name': 'Indisponibilidade do Barbeiro',
                'verbose_name_plural': 'Indisponibilidades dos Barbeiros',
                'unique_together': {('barbeiro', 'data_inicio', 'data_fim')},
            },
        ),
    ]
