# Generated by Django 5.2.1 on 2025-11-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0004_barbeiroindisponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id_fixo', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('nome_exibicao', models.CharField(default='Barbearia A Tesoura de Ouro', help_text='O nome que aparece no header do chat.', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Faça upload do logo (idealmente .png transparente)', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuração Geral do Chat',
                'verbose_name_plural': 'Configuração Geral do Chat',
            },
        ),
    ]
