# Generated by Django 5.2.1 on 2025-11-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0005_configuracaogeral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaogeral',
            options={'verbose_name': 'Configuração Geral e Horários', 'verbose_name_plural': 'Configuração Geral e Horários'},
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='abre_domingo',
            field=models.BooleanField(default=False, verbose_name='Abre aos Domingos?'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='abre_sabado',
            field=models.BooleanField(default=True, verbose_name='Abre aos Sábados?'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='endereco_loja',
            field=models.CharField(blank=True, help_text='Endereço que aparecerá abaixo do chat', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_abertura',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Abertura (Seg-Sex)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_abertura_domingo',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), null=True, verbose_name='Abertura (Domingo)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_abertura_feriado',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Abertura (Feriado)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_abertura_sabado',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Abertura (Sábado)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_fechamento',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Fechamento (Seg-Sex)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_fechamento_domingo',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True, verbose_name='Fechamento (Domingo)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_fechamento_feriado',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), null=True, verbose_name='Fechamento (Feriado)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_fechamento_sabado',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='Fechamento (Sábado)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_fim_almoco',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='Fim Almoço (Seg-Sex)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='hora_inicio_almoco',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Início Almoço (Seg-Sex)'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='intervalo_agendamento',
            field=models.IntegerField(choices=[(15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos (Padrão)'), (60, '60 minutos (1 hora)')], default=30, help_text='Define os blocos de tempo da agenda (ex: 30 em 30 min).', verbose_name='Intervalo da Grade'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='link_maps',
            field=models.URLField(blank=True, help_text='Link do Google Maps/Waze', null=True),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='trabalha_feriados',
            field=models.BooleanField(default=False, verbose_name='Abre em Feriados?'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='nome_exibicao',
            field=models.CharField(default='Barbearia A Tesoura de Ouro', max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora e 30 min'), (120, '2 horas'), (150, '2 horas e 30 min'), (180, '3 horas')], help_text='A duração deve ser múltipla de 30 min para otimizar a agenda.'),
        ),
    ]
