# Generated by Django 5.2.8 on 2025-11-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0006_alter_configuracaogeral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbeiroindisponibilidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configuracaogeral',
            options={'verbose_name': 'Configuração Geral'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do serviço no momento do agendamento.', max_digits=6, null=True, verbose_name='Valor Cobrado (R$)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='abre_domingo',
            field=models.BooleanField(default=False, verbose_name='Abre Domingo?'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='abre_sabado',
            field=models.BooleanField(default=True, verbose_name='Abre Sábado?'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='endereco_loja',
            field=models.CharField(blank=True, help_text='Endereço no rodapé', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='intervalo_agendamento',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min (Padrão)'), (60, '1 hora')], default=30, verbose_name='Grade de Tempo'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='link_maps',
            field=models.URLField(blank=True, help_text='Link do Google Maps', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='trabalha_feriados',
            field=models.BooleanField(default=False, verbose_name='Abre Feriados?'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.IntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora e 30 min'), (120, '2 horas'), (150, '2 horas e 30 min'), (180, '3 horas')], help_text='Duração múltipla de 30 min'),
        ),
    ]
