# Generated by Django 5.2.8 on 2025-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia_app', '0007_alter_barbeiroindisponibilidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='mensagem_compartilhamento',
            field=models.TextField(default='Ei! Conheça nossa Barbearia com esse chatbot super prático para agendamentos. Clique aqui:', help_text='Texto que aparecerá no WhatsApp quando o cliente clicar em compartilhar.', verbose_name='Mensagem de Compartilhamento'),
        ),
    ]
